name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SAT" # runs weekly on Saturday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v16
        with:
          pr-title: "Update flake.lock"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: automerge
          number: ${{ steps.update.outputs.pull-request-number }}
      - uses: "pascalgn/automerge-action@v0.15.6"
        env:
          MERGE_METHOD: rebase
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN_FOR_UPDATES }}"
      # - uses: juliangruber/merge-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     number: ${{ steps.update.outputs.pull-request-number }}
      #     method: rebase
